### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by azuryl** [biomedical-cybernetics/Relative-importance-and-activation-pruning#2]
Dear @biomedical-cybernetics @silence1024 
I use the 'wikitext2' replace "c4"
and baffo32/decapoda-research-llama-7B-hf

but
loading calibdation data
dataset loading complete
Traceback (most recent call last):
  File "/home/delight-gpu/Workspace2/azuryl/Relative-importance-and-activation-pruning/main.py", line 151, in <module>
    main()
  File "/home/delight-gpu/Workspace2/azuryl/Relative-importance-and-activation-pruning/main.py", line 86, in main
    prune_ria(args, model, tokenizer, device, prune_n=prune_n, prune_m=prune_m)
  File "/home/delight-gpu/Workspace2/azuryl/Relative-importance-and-activation-pruning/lib/prune.py", line 183, in prune_ria
    inps, outs, attention_mask, position_ids = prepare_calibration_input(args, model, dataloader, device)
  File "/home/delight-gpu/Workspace2/azuryl/Relative-importance-and-activation-pruning/lib/prune.py", line 102, in prepare_calibration_input
    inps = torch.zeros((args.nsamples, model.seqlen, model.config.hidden_size), dtype=dtype, device=device)
  File "/home/azuryl/anaconda3/envs/prune_ria/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by silence1024** [comment]
Hi @azuryl, it means it can't find any CUDA-compatible GPUs on your system. Please make sure your Nvidia-driver is installed on your server.

**Comment by azuryl** [comment]
> Hi @azuryl, it means it can't find any CUDA-compatible GPUs on your system. Please make sure your Nvidia-driver is installed on your server.

Dear @silence1024  I just tried, GPU are installed  in  Relative-importance-and-activation-prunin enviorment
(prune_ria) azuryl@light-28d:/home/delight-gpu/Workspace2/azuryl/Relative-importance-and-activation-pruning$ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import torch
 >>> print(torch.cuda.is_available())
True
>>> torch.cuda.device_coun
I wirte a script, prune.sh:

model='baffo32/decapoda-research-llama-7B-hf' #'openlm-research/open_llama_3b_v2' #'princeton-nlp/Sheared-LLaMA-1.3B'
nGPU='5'
CUDA_VISIBLE_DEVICES=$nGPU python main.py \
	--model $model \
	--prune_method wanda \
	--sparsity_ratio 0.5 \
	--sparsity_type 2:4 \
    --calib_dataset 'wikitext2'\
	--save \
when it run
but in [main.py](https://github.com/biomedical-cybernetics/Relative-importance-and-activation-pruning/blob/main/main.py)#L10

print("cuda is available",torch.cuda.is_available())
is False
print('# number gpus: ', torch.cuda.device_count())
is 0

**Comment by azuryl** [comment]
fix
