### ISSUE TITLE
请问YOUR_MODEL_NAME填什么？

### ISSUE THREAD

**Issue by chixu-xmu** [biomedical-cybernetics/Relative-importance-and-activation-pruning#4]
我使用了 python main.py --model LLaMA3-8B --prune_method wanda --sparsity_ratio 0.5 --sparsity_type unstructured --save命令，报错为
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and **it looks like LLaMA3-8B is not the path to a directory** containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by silence1024** [comment]
Hi @lofty11, YOUR_MODEL_NAME应该填写相应的模型路径。如果您在中国大陆，无法访问huggingface，您需要在huggingface手动下载模型文件至本地然后将文件地址更换YOUR_MODEL_NAME。如果您可以访问huggingface，则只需要填写huggingface相应模型仓库名称，他会自动下载。

BTW，LLaMA模型需要先获得许可才能下载，例如你的LLaMA3-8b。这里是申请的网址：https://huggingface.co/meta-llama/Meta-Llama-3-8B/
当你获得许可后，可以直接输入该模型名称meta-llama/Meta-Llama-3-8B进行下载。

**Comment by chixu-xmu** [comment]
非常感谢！在一个镜像网站找到了，已经成功运行！





------------------ 原始邮件 ------------------
发件人: silence1024 ***@***.***&gt;
发送时间: 2024年6月24日 12:37
收件人: biomedical-cybernetics/Relative-importance-and-activation-pruning ***@***.***&gt;
抄送: xuchichichi ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [biomedical-cybernetics/Relative-importance-and-activation-pruning] 请问YOUR_MODEL_NAME填什么？ (Issue #4)





 
Hi @lofty11, YOUR_MODEL_NAME应该填写相应的模型路径。如果您在中国大陆，无法访问huggingface，您需要在huggingface手动下载模型文件至本地然后将文件地址更换YOUR_MODEL_NAME。如果您可以访问huggingface，则只需要填写huggingface相应模型仓库名称，他会自动下载。
 
BTW，LLaMA模型需要先获得许可才能下载，例如你的LLaMA3-8b。这里是申请的网址：https://huggingface.co/meta-llama/Meta-Llama-3-8B/
 当你获得许可后，可以直接输入该模型名称meta-llama/Meta-Llama-3-8B进行下载。
